config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bookmarks
  root 'bookmarks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_url.rb
# Public: BaseUrl parses a url and trims it to its base url.
class BaseUrl

  def initialize url
    @original_url = url
  end

  # Public: Trim a Url to its base.
  #
  # Returns the base Url.
  def trim
    return nil if @original_url.nil?

    # Using Addressable::URI#join with '/' is a trick to get back
    # only the base url with an appended '/'
    base_url = Addressable::URI.parse(@original_url).join('/').to_s
    if base_url.size > 1
      base_url.gsub /\/$/, ""
    else
      @original_url
    end
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :site, counter_cache: true

  validates :name, presence: true
  validates :url,  presence: true, uniqueness: true, http_url: true
  validates :short_url, http_url: true
  validate :site_has_matching_base_url

  def self.search term
    where "lower(name) LIKE lower(:term) OR \
           lower(url) LIKE lower(:term) OR \
           lower(short_url) LIKE lower(:term) OR \
           lower(:tag) = ANY (tags)",
           term: "%#{term}%", tag: term
  end

  private
    def site_has_matching_base_url
      if url_changed? && BaseUrl.new(url).trim != site.try(:url)
        errors.add :site, 'base URL does not match URL'
      end
    end
end

app/models/site.rb
# A Site groups bookmarks togehter by their base URL.
# Therefore the AR class will always "sanitize" non-base
# URLs used in interacting with this class by trimming the
# URL to its base URL. This is achieved by using a Serializer.
class Site < ApplicationRecord

  class UrlSerializer
    def dump value
      BaseUrl.new(value).trim
    end
    def load value
      value
    end
  end
  private_constant :UrlSerializer

  has_many :bookmarks, dependent: :destroy

  serialize :url, UrlSerializer.new 
  validates :url, presence: true, uniqueness: true, http_url: true

  def has_bookmarks?
    bookmarks_count > 0
  end

  def single_bookmark?
    bookmarks_count == 1
  end

  # Deletes the Site if there are no more bookmarks associated
  def destroy_if_orphaned
    destroy unless has_bookmarks?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = params[:q].blank? ? Bookmark.all : Bookmark.search(params[:q])
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bss = BookmarkSiteSynchronizer.new(@bookmark)

    respond_to do |format|
      if @bss.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    @bss = BookmarkSiteSynchronizer.new(@bookmark)
    respond_to do |format|
      if @bss.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    BookmarkSiteSynchronizer.new(@bookmark).destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Additionally convert comma separated tags into an array.
    def bookmark_params
      bmark_params = params.require(:bookmark).permit(:name, :url, :short_url, :tags)
      if bmark_params.has_key? :tags
        bmark_params[:tags] = bmark_params[:tags].split(',').map(&:strip)
      end
      bmark_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper

  def textify_tags value
    if value.is_a? Array
      value.join ', '
    else
      value
    end
  end
end

app/views/bookmarks/_form.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <%= form_for(bookmark) do |f| %>
      <% if bookmark.errors.any? %>
        <div id="error_explanation">
          <h2 class="alert alert-danger" role="alert"><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
          <ul>
          <% bookmark.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: true %>
      </div>

      <div class="field">
        <%= f.label :url %>
        <%= f.text_field :url, placeholder: true %>
      </div>

      <div class="field">
        <%= f.label :short_url %>
        <%= f.text_field :short_url, placeholder: true %>
      </div>

      <%# Using SimpleForm would make this much easier as we could use a custom input. %>
      <div class="field">
        <%= f.label :tags %>
        <%= f.text_field :tags, placeholder: true, value: textify_tags(f.object.tags) %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/_search_form.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <%= form_tag request.path, method: :get, class: 'search with-turbolinks', enforce_utf8: false, id: 'search_form' do |f| %>
      <%= text_field_tag :q, params[:q], placeholder: 'Enter search term' %>
      <%= link_to '×', params.permit.merge(q: nil), style: params.has_key?(:q) ? '' : 'display:none' %>
    <% end %>
  </div>
</div>

app/views/bookmarks/_tags.html.erb
<% tags.each do |tag| %>
  <span class="badge badge-info"><%= tag %></span>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="row">
  <div class="col-12">
    <h1>Editing Bookmark</h1>
  </div>
</div>

<%= render 'form', bookmark: @bookmark %>

<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <%= link_to t('show_action'), @bookmark %> |
    <%= link_to t('back_action'), bookmarks_path %>
  </div>
</div>

app/views/bookmarks/index.html.erb
<%= render partial: 'layouts/notice'%>

<div class="row">
  <div class="col-12">
    <h1><%= t('page.bookmarks')%></h1>
  </div>
</div>

<%= render partial: 'search_form' %>

<% if @bookmarks.present? %>
  <section class="bookmarks">

    <% @bookmarks.each do |bookmark| %>
      <div class="row">
        <article class="col-12 col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
          <div class="row">
            <div class="bookmark1 col-sm-10">
              <%= link_to bookmark.url do %>
                <h2><%= bookmark.name %></h2>
                <div><small><%= bookmark.url %></small></div>
              <% end %>

              <small>
                Website: <%= link_to bookmark.site.url, bookmark.site.url %>
                <% if bookmark.short_url.present? %> 
                  |
                  Short URL: <%= link_to bookmark.short_url, bookmark.short_url %>
                <% end %>
              </small>
              <div>
                <%= render partial: 'tags', locals: { tags: bookmark.tags } %>
              </div>

            </div>
            <nav class="col-sm-2">
              <p><%= link_to t('show_action'), bookmark %></p>
              <p><%= link_to t('edit_action'), edit_bookmark_path(bookmark) %></p>
              <p><%= link_to t('destroy_action'), bookmark, method: :delete, data: { confirm: t('confirm') } %></p>
            </nav>
          </div>
        </article>
      </div>
    <% end %>
  </section>
<% else %>
  <div class="row">
    <div class="col-12 col-sm-10 offset-sm-1">
      <h2 class="text-center"><%= params.has_key?(:q) ? t('not_found', term: params[:q]) : t('no_bookmarks') %></h2>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="col-12 col-sm-10 offset-sm-1 col-lg8 offset-lg-2">
    <%= link_to t('nav.new_bookmark'), new_bookmark_path %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="row">
  <div class="col-12">
    <h1><%= t('page.new_bookmark') %></h1>
  </div>
</div>

<%= render 'form', bookmark: @bookmark %>

<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <%= link_to t('back_action'), bookmarks_path %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<%= render partial: 'layouts/notice'%>

<div class="row">
  <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
 
    <p>
      <strong>Name:</strong>
      <%= @bookmark.name %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @bookmark.url %>
    </p>

    <p>
      <strong>Short url:</strong>
      <%= @bookmark.short_url %>
    </p>

    <p>
      <strong>Site:</strong>
      <%= @bookmark.site.url %>
    </p>
    <p>
      <strong>Tags:</strong>
      <%= render partial: 'tags', locals: { tags: @bookmark.tags } %>
    </p>
  </div>
</div>

<%= link_to t('edit_action'), edit_bookmark_path(@bookmark) %> |
<%= link_to t('back_action'), bookmarks_path %>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>